version: "2"
services:
 db:
   image: mysql
   environment:
     - MYSQL_ROOT_PASSWORD=rootPassw0rd
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:1337
   volumes:
     - .:/app
   ports:
     - "1337:1337"
   links:
     - db:nrin.myd.infomaniak.com
   depends_on:
     - db
   environment:
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD