# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='service',
            field=models.CharField(choices=[(b'bricolage', b'Bricolage'), (b'jardinage', b'Jardinage'), (b'demenagement', b'Demenagement'), (b'menage-repassage', b'Menage/Repassage'), (b'assemblage-meuble', b'Assemblage meuble'), (b'informatique', b'Informatique'), (b'ramassage-livraison', b'Rammassage et livraison'), (b'animaux', b'Animaux'), (b'evenementiel', b'Evenementiel'), (b'prestation-administratif', b'Prestations Administratif'), (b'service-personne', b'Service a la personne')], default='T', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail',
            name='user_type',
            field=models.CharField(choices=[(b'A', b'ASKER'), (b'T', b'TASKER')], default=b'A', max_length=1),
        ),
        migrations.AlterField(
            model_name='mail',
            name='address',
            field=models.EmailField(max_length=254),
        ),
    ]
